### ISSUE TITLE
GitHub link doesn't work

### ISSUE THREAD

**Issue by mmmeyers** [learn-co-curriculum/sql-databases-and-text-editors-readme#4]
GitHub link at top of page goes to https://github.com/learn-co-students/databases-and-text-editors-v-000, which is a 'Page not found.'

This isn't a lesson that requires a fork so it's not super urgent. That link should point to https://github.com/learn-co-curriculum/sql-databases-and-text-editors-readme

**Comment by AnnJohn** [comment]
Thanks! Will look into it.
