### ISSUE TITLE
Learn IDE clarification needed

### ISSUE THREAD

**Issue by ivalentine** [learn-co-curriculum/sql-databases-and-text-editors-readme#7]
This lesson should include a clarification that for Learn IDE users, the Learn IDE is their text editor — a separate text editor is not needed, nor will it work.

**Comment by maxwellbenton** [comment]
Hi @ivalentine,

Thank you for opening this issue. We've recently updated the materials in this section and incorporated changes to this lab based on your feedback. We've replaced the reference to Sublime with Learn IDE to avoid this confusion for students in the future.

Thank you for contributing to this lesson!
