### ISSUE TITLE
Native Environment

### ISSUE THREAD

**Issue by abourke09** [learn-co-curriculum/sql-databases-and-text-editors-readme#8]
This lesson says to use a text editor like Sublime but the Help article here (http://help.learn.co/workflow-tips/local-environment/when-should-i-set-up-a-local-environment) says to wait until the SinatraProject in completed before switching to native from the Learn IDE.

**Comment by maxwellbenton** [comment]
Hi @abourke09,

Thank you for opening this issue. We've recently updated the materials in this section and incorporated changes to this lab based on your feedback. We've replaced the reference to sublime with Learn IDE to avoid this confusion for students in the future.

Thank you for contributing to this lesson!
